# Generated by Django 5.0.3 on 2024-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='plot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='released',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='end_date',
            field=models.DateTimeField(help_text='Date time of reading session end', null=True),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='start_date',
            field=models.DateTimeField(help_text='Date time of reading session start'),
        ),
        migrations.AlterField(
            model_name='userbookstat',
            name='last_session_end',
            field=models.DateTimeField(help_text='Datetime of the end of last reading session', null=True),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
