# Generated by Django 5.0.3 on 2024-04-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_plot_book_released_and_more'),
        ('films', '0004_alter_film_genre'),
        ('tracker', '0004_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.genre'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
