# Generated by Django 5.0.3 on 2024-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookstat',
            name='pages_read_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbookstat',
            name='sessions_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbookstat',
            name='total_reading_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
