# Generated by Django 5.0.3 on 2024-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookstat',
            name='reading_speed',
            field=models.FloatField(help_text='Reading speed in pages per minute'),
        ),
    ]
