# Generated by Django 5.0.3 on 2024-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='owners', to='books.book'),
        ),
    ]
