# Generated by Django 5.0.3 on 2024-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_plot_book_released_and_more'),
        ('films', '0001_initial'),
        ('tracker', '0002_user_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='film_owners', to='films.film'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='book_owners', to='books.book'),
        ),
    ]
