# Generated by Django 5.0.3 on 2024-05-25 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reading_time', models.IntegerField(blank=True, null=True)),
                ('total_sessions_count', models.IntegerField(blank=True, null=True)),
                ('total_pages_read_count', models.IntegerField(blank=True, null=True)),
                ('average_reading_speed', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
