# Generated by Django 5.0.3 on 2024-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstat',
            old_name='total_sessions_count',
            new_name='total_book_sessions_count',
        ),
        migrations.AddField(
            model_name='userstat',
            name='total_film_sessions_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstat',
            name='total_minutes_watched',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
