# Generated by Django 5.0.3 on 2024-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_total_sessions_count_userstat_total_book_sessions_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='average_reading_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
