# Generated by Django 5.0.3 on 2024-04-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_book_plot_book_released_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('released', models.DateField()),
                ('poster', models.FileField(blank=True, null=True, upload_to='')),
                ('length', models.IntegerField(help_text='The length of the film in minutes')),
                ('plot', models.TextField(blank=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='films', to='films.film')),
                ('directors', models.ManyToManyField(blank=True, related_name='films', to='films.film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.genre')),
            ],
        ),
        migrations.CreateModel(
            name='WatchingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Date time of watching session start')),
                ('end_date', models.DateTimeField(help_text='Date time of watching session start')),
                ('watching_time', models.IntegerField(blank=True, help_text='The number of minutes the user has watched')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFilmStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_watching_time', models.IntegerField(blank=True, help_text='The number of minutes the user has watched totally')),
                ('sessions_count', models.IntegerField(blank=True)),
                ('last_session_end', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
    ]
