# Generated by Django 5.0.3 on 2024-04-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_directors_actor_film_actors'),
        ('tracker', '0004_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.genre'),
        ),
    ]
