# Generated by Django 5.0.3 on 2024-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilmstat',
            name='last_session_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userfilmstat',
            name='sessions_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilmstat',
            name='total_watching_time',
            field=models.IntegerField(blank=True, help_text='The number of minutes the user has watched totally', null=True),
        ),
    ]
