# Generated by Django 5.0.3 on 2024-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_userfilmstat_last_session_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
