# Generated by Django 5.0.3 on 2024-05-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_film_actors_alter_film_id_delete_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.CharField(blank=True, null=True),
        ),
    ]
