# Generated by Django 5.0.3 on 2024-05-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_poster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='director',
            unique_together=set(),
        ),
    ]
