# Generated by Django 5.0.3 on 2024-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_director_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
